### ISSUE TITLE
{comment_link} not linking to comment

### ISSUE THREAD

**Issue by atomGit** [isabelc/Comment-Notifier-No-Spammers#12]
not exactly sure this is an issue with the plug-in - seems to have started with the recent WP update

WP 4.7.3
Lightweight Subscribe To Comments 1.5.3
link code: `<a href="{comment_link}">Click here</a> here to read the rest.`

clicking the link in the email (or from anywhere else) scrolls the browser document to the bottom of the page, bypassing the comment, however if i place my cursor in the address bar and 'enter', it scrolls to the comment - refreshing the page (F5) also scrolls to the bottom and not the comment

example link:

`http://12bytes.org/articles/tech/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs/comment-page-4#comment-703 `

browser console doesn't seem to tell me anything interesting

**Comment by isabelc** [comment]
Sorry for the delay. I tried your link in Firefox and Chrome and it's working fine. If you're still having this issue, it would more likely be a browser issue. We're left to the mercy of the browsers--and how they implement the "jumping down" on the page.

**Comment by atomGit** [comment]
looks like this may have been a browser bug - i use FF also, but the issue isn't an issue anymore in 52.0.1  :)
